CREATE TABLE IF NOT EXISTS comic_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_slug VARCHAR NOT NULL UNIQUE,
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tạo index cho comic_slug để tối ưu tìm kiếm
CREATE INDEX IF NOT EXISTS idx_comic_stats_slug ON comic_stats(comic_slug);

-- Tạo trigger để tự động cập nhật updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_comic_stats_updated_at
    BEFORE UPDATE ON comic_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();